name: CI/CD

on:
  push:
    branches: [main, dev]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.2"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install create-dmg (Yarn install)
        run: yarn install

      - name: Fastlane Build
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: "release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
